# frozen_string_literal: true

require_relative 'smart_router/provider'
require_relative 'smart_router/operation'
require_relative 'smart_router/precision_math'
require_relative 'smart_router/hard_constraints'
require_relative 'smart_router/scoring_engine'
require_relative 'smart_router/simulation_engine'
require_relative 'smart_router/analytics_reporter'
require_relative 'smart_router/historical_analyzer'
require_relative 'smart_router/audit_logger'
require_relative 'smart_router/rule_engine'
require_relative 'smart_router/anomaly_detector'
require_relative 'smart_router/load_balancer'
require_relative 'smart_router/financial_ledger'
require_relative 'smart_router/requisite_optimizer'
require_relative 'smart_router/machine_readable_reporter'
require_relative 'smart_router/multi_currency_router'
require_relative 'smart_router/routing_policy_config'
require_relative 'smart_router/gateway_circuit_breaker'
require_relative 'smart_router/self_healing_engine'
require_relative 'smart_router/dynamic_sla_monitor'
require_relative 'smart_router/replay_simulation_harness'
require_relative 'smart_router/fraud_and_risk_scorer'
require_relative 'smart_router/cost_optimizer'
require_relative 'smart_router/dynamic_fee_model'
require_relative 'smart_router/split_routing_engine'
require_relative 'smart_router/router'

module SmartRouter
  VERSION = '1.0.0'
end
